# Generated by Django 5.1.7 on 2025-03-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=100, verbose_name='販売経路')),
                ('product', models.CharField(max_length=100, verbose_name='商品')),
                ('model', models.CharField(max_length=100, verbose_name='モデル')),
                ('purchase_date', models.DateField(verbose_name='購入日')),
                ('quantity', models.PositiveIntegerField(verbose_name='購入数')),
            ],
        ),
    ]
