# Generated by Django 5.1.7 on 2025-03-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_channel', models.CharField(max_length=255, verbose_name='注文経路')),
                ('product_name', models.CharField(max_length=255, verbose_name='商品名')),
                ('category', models.CharField(max_length=255, verbose_name='カテゴリ')),
                ('order_date', models.DateField(verbose_name='注文日')),
                ('customer_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='顧客番号')),
                ('order_quantity', models.PositiveIntegerField(verbose_name='注文数')),
            ],
        ),
    ]
