# Generated by Django 5.1.7 on 2025-03-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0002_orderhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='category',
            field=models.CharField(choices=[('PC', 'PC'), ('SE品', 'SE品')], default='PC', max_length=10, verbose_name='区分'),
            preserve_default=False,
        ),
    ]
